### ISSUE TITLE
acrotest.tex fails to compile if .aux file is missing

### ISSUE THREAD

**Issue by oetiker** [oetiker/acronym#20]
Hi @marsmee 
something still seems not right ... the acrotest.tex file does not compile if there is no aux file ... I have added automated testing now ...  can you have a look?

**Comment by marsmee** [comment]
Hi @oetiker,
I figured out that this behaviour/bug was introduced in commit  89da3388a04e0e4c2522d7ab215f5de3a769100d back in 2018. Please give me some more time and I will try to fix the problem.

**Comment by oetiker** [comment]
thank you @marsmee !
