### ISSUE TITLE
Acronym section automatically generated from \newacro entries?

### ISSUE THREAD

**Issue by HJAllen** [oetiker/acronym#3]
I really like the flexibility of the \newacro command for adding acronyms as I am writing.  I also understand the explanation of the use of the \newacro command for using acronyms without generating an acronym list.

Is it possible to automatically generate an acronym section from \newacro entries when the document is processed?
Thanks,
Joel

**Comment by oetiker** [comment]
I guess it could be implemented :-) but it is not presently a feature
