### ISSUE TITLE
Spacing in front of description when using acfi and acf

### ISSUE THREAD

**Issue by PyTeXJulia** [oetiker/acronym#33]
Although hskip was removed, I still get some strange spacing in front of the full description when using \acf and \acfi.

**Comment by marsmee** [comment]
Hi @PyTeXJulia ,

many thanks for your report. Could you please provide an MWE?

**Comment by PyTeXJulia** [comment]
\documentclass[11pt, a4paper, headings=onelinechapter, parskip=half]{scrbook}

\usepackage{luatex85}
\usepackage[main=english]{babel}		% Sprachen
\usepackage{fontspec}					% Schriftpaket für LuaTeX
\usepackage{amsmath}

%--------------------------------
%conventions
\usepackage[nohyperlinks, withpage]{acronym}


%-------------------------
\begin{document}

\chapter{Acronym}

\begin{acronym}[LONGEST] \itemsep6pt

\acro{KÜRZEL}[ABKÜRZUNG]{\acroextra{\makebox[18mm][l]{}}BESCHREIBUNG}
\newcommand{\acrounit}[1]{
  \acroextra{\makebox[18mm][l]{}}
}

\renewcommand*{\aclabelfont}[1]{\textsf{\acsfont{#1}}}

\acro{ta}[$t_\text{a}$]{\acrounit{[T]}drawdown time}
\acro{za}[$z_\text{a}$]{\acrounit{[L]}change in water level}
\end{acronym}

\chapter{Random text}

Based on the investigations of X vessel wave induced drawdowns can be simplified by a uniformly decreasing water level characterised by a constant drawdown rate (\acf{za} during \acf{ta}).

\end{document}

**Comment by marsmee** [comment]
Hello @PyTeXJulia,

I've taken a look at your example and found the following problem:
```latex
\newcommand{\acrounit}[1]{
  \acroextra{\makebox[18mm][l]{}}
}
```
This command introduces some white-space due to "active" newlines. Try the following instead:
```latex
\newcommand{\acrounit}[1]{%
  \acroextra{\makebox[18mm][l]{}}%
}
```

For future issue reports, please provide an MWE (and preferably a screenshot) and use appropriate code blocks, for example:
````markdown
```latex
\documentclass[a4paper]{article}
```
````
