### ISSUE TITLE
\ac always shows short form when called inside pdftooltip

### ISSUE THREAD

**Issue by pacho2** [oetiker/acronym#37]
Hello,

At first thanks for your package, it is really useful to easily track all the acronyms and generate the list of them.

One thing I was trying to achieve was to, instead of providing an hyperlink to the list, show the acronym long forms in a tooltip. 

I achieved that defining a new command (I called it \act, and its variants) that at the end calls the following relying on pdftooltip from https://ctan.org/pkg/pdfcomment
\pdftooltip{\ac{#1}}{\acl*{#1}}

even simpler form:
\pdftooltip{\ac{DAG}}{TEST}

fails in the same way

The problem is that, for some reason, when \ac is called inside pdftooltip, it always prints thee short form, even for the first time... and I fail to understand why. For all the other cases it works nice, but that problem with \ac makes me wonder about what could be happening (and it's a bit sad because, apart from that, everything else works)

Thanks a lot for your help

**Comment by marsmee** [comment]
This might be related to #6 or #11.

Could you have a look at the `.aux` file to check if there where multiple executions of the acronym retrieval, please? As described at https://github.com/oetiker/acronym/issues/11#issuecomment-609094234, some packages like `tabularx` rely on commands that are free of side effect, which `\ac` is definitely not. So, the best option is to use only the side-effect free commands of the `acronym` package like `\acs*`  or `\acl*` inside other commands.

**Comment by pacho2** [comment]
As I see in the aux, it seems it's not called before it fails... I attach the aux file and a more reduced tex example

One thing about using the side-effect free commands... with them I would need to manually expand the first time I use an acronym, no? 

Thanks
[test_minim.zip](https://github.com/oetiker/acronym/files/5135297/test_minim.zip)

**Comment by marsmee** [comment]
If you have a look at the definition of `\pdftooltip` you can see that the argument for the visible text (`#2`) is used three times before it is actually printed.

```latex
\newcommand{\pdftooltip}[3][]%
{%
  % ...
  \ifmmode%
    % ...
  \else%
    \expandafter\pc@encode@PDF{#3}%
    \ifpc@lopt@disable%
      #2%
    \else%
      \hspace*{0pt}%
      \settowidth{\pc@box@width}{#2}%      <-- used here
      \settoheight{\pc@box@height}{#2}%    <-- and also here
      \settodepth{\pc@box@depth}{#2}%      <-- and here again
      \ifpdf%
        \pdfannot width \the\pc@box@width height \the\pc@box@height depth \the\pc@box@depth%
        % ...
        #2%    <-- this is the printed part
      \else%
        % ...
      \fi%
    \fi%
  \fi%
  % ...
}%
```

Generally speaking, the `pdfcomment` package does the same as the `tabularx` package. Both measure the sizes of the given argument and thus execute the command. As you can see here, the width is actually calculated from the full acronym:
![acronym](https://user-images.githubusercontent.com/29836061/91464475-e992d100-e88c-11ea-940f-61afac74e949.png)

> One thing about using the side-effect free commands... with them I would need to manually expand the first time I use an acronym, no?

Unfortunately, there seems to be no way to detect if `\ac` is used within another command. Maybe some LaTeX guru knows an answer to this, but I definitely don't. All I can provide to you is some workaround if you are going to use this very often.

```latex
\makeatletter
\newcommand{\actooltip}[1]{%
  \expandafter\ifx\csname AC@\AC@prefix#1\endcsname\AC@used
    \pdftooltip{\acs{#1}}{\acl{#1}}%
  \else
    \pdftooltip{\acf{#1}}{\acl{#1}}%
  \fi
}
\makeatother
```

**Comment by pacho2** [comment]
Ah, thanks a lot for the explanation and the workaround 

Best regards
