### ISSUE TITLE
Irregular vertical spacing between acronyms

### ISSUE THREAD

**Issue by ldj01** [oetiker/acronym#4]
When using a large acronym list with only a few printed (using the "printonlyused" option), occasionally extra vertical space is introduced between the printed items.  Here is a minimal example that illustrates the issue:
```
\documentclass[12pt]{book}
\usepackage[printonlyused]{acro}
\begin{document}
\ac{XXX}
\ac{YYY}
\begin{acronym}[XXXXXXXXXX]
\acro{XXX}{xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx}
\acro{101}{}
\acro{102}{}
\acro{103}{}
\acro{104}{}
\acro{105}{}
\acro{106}{}
\acro{107}{}
\acro{108}{}
\acro{109}{}
\acro{110}{}
\acro{YYY}{xxxx}
\end{acronym}
\end{document}

```
The spacing between the XXX and YYY definitions is larger than it should be.  The spacing between the two definitions is corrected if any of the following is done:
  - Reduce the number of unused acronyms (101 - 110).
  - Reduce the length of the defined item width ("XXXXXXXXXX").
  - Reduce the length of the XXX acronym definition.

I think I've traced the problem to the \begingroup block in the \AC@@acro definition in acronym.sty (2015/03/21, v1.41).  Multiple \@bsphack \@esphack pairs (introduced by each unused acronym) appear to add white space to the previous printed acronym definition so that, at some point the definition spans an additional line.

I'm not sure that my description is accurate, but I have found that adding "\ignorespaces" after the \endgroup seems to resolve the issue.

**Comment by oetiker** [comment]
you can 'edit' the dtx file directly in github and create a pull request !

**Comment by ldj01** [comment]
The issue appears to be resolved with the most recent merge, so I will close this issue.  Thanks again!
