### ISSUE TITLE
Make acronym index sort alphabetically 

### ISSUE THREAD

**Issue by JavanXD** [oetiker/acronym#43]
Hey, I came across your great acronym package but I noticed when I googled for "latex acronym sort alphabetical" I found users from 2011 asking the same problem.

Could you add support for sorting the index alphabetically? 

```
% Acronyms (Abkürzungsverzeichnis)
\usepackage{acronym}  
```
...
```
% Abkürzungsverzeichnis
% im Text dann mit \ac{DAST} referenzieren
\section*{Abkürzungsverzeichnis}
\addcontentsline{toc}{section}{Abkürzungsverzeichnis}
\begin{acronym}
    \acro{B}{Blub}
    \acro{A}{Bla}
%...
\end{acronym}
\clearpage
```

**Comment by oetiker** [comment]
Hi Javan

sorting is a can or worms, and normaly solved via external programs ... in any event, just list en acronyms in th acronym environment in the order you deem appropriate ... in that way they are already sorted ... 

maybe I don't see what the problem is.
