### ISSUE TITLE
Capitalization of acronym custom plural

### ISSUE THREAD

**Issue by blefloch** [oetiker/acronym#45]
I'm encountering two related bugs.  First the easy one: the definition of `\@Acp` incorrectly uses `\acsp` twice, which should be replaced by `\Acsp`.  Second, commands such as `\AC@Aclp` fail to capitalize the full form in case a custom plural `\csname fn@#1@PL\endcsname` is available: `\AC@Aclp` calls `\AC@aclp` after setting the `\ifAC@upper` switch, but the definition
```
\newcommand*\AC@aclp[1]{%
  \ifcsname fn@#1@PL\endcsname
  \csname fn@#1@PL\endcsname
  \else
  \AC@acl{#1}s%
  \fi
}
```
means that `\csname fn@#1@PL\endcsname` is used directly, without being processed with `\ifAC@upper \@firstupper` etc. (correctly used in the standard case that passes through `\AC@get`).

**Comment by oetiker** [comment]
hi @blefloch a PR is highly welcome !
