### ISSUE TITLE
\Iac problem, after acronym is used

### ISSUE THREAD

**Issue by 07U** [oetiker/acronym#9]
A way to reproduce the error:
1. Open acrotest.tex
2. In the acronym environment, add: _\acroindefinite{IC}{an}{an}_.
3. Add to the text, somewhere after _\acp{IC}_, the command _\Iac{IC}_.

Note:
I'm not sure it is helping, but loading the package with the option |nolist|, makes the problem disappear.
Also, erasing the first _\acp{IC}_ or the added _\acroindefinite{IC}{an}{an}_, will make the file compile as expected.

**Comment by marsmee** [comment]
I think this has been fixed.

**Comment by 07U** [comment]
Dear marsmee,

I have checked the current acrotest.tex file, but the scenario there is not the same as I presented above.
Please erase the line "\Iac{IC} popped up unexpectedly." and add (for instance) "\Iac{IC} is another name for a chip." at the end of the "Some testing fundamentals" subsection.
